### ISSUE TITLE
is it possible to skip adding the domain in authentication

### ISSUE THREAD

**Issue by f1-outsourcing** [bit/matrix-synapse-imap#2]
I have a test setup, and this does not work, because somewhere a domain is being added.

curl -XPOST -d '{"type":"m.login.password", "user":"testuser", "password":"xxx"}' "http://test.local:8018/_matrix/client/r0/login

Mail server logs this
auth-worker(26902): pam(testuser@xxx.xxxxxxx.xxxxx,8.8.8.8,<PQeZ/F6ror3UGsEl>): unknown user

**Comment by bit** [comment]
merged your pull request
